backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "team"
    label: "Team Members"
    folder: "data"
    create: true
    slug: "team"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Active", name: "active", widget: "boolean"}
      - {label: "Social", name: "social", widget: "object", fields: [
          {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
          {label: "GitHub", name: "github", widget: "string", required: false}
        ]}
  - name: "programs"
    label: "Programs"
    folder: "data"
    create: true
    slug: "programs"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Details", name: "details", widget: "list"}
  - name: "projects"
    label: "Projects"
    folder: "data"
    create: true
    slug: "projects"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Student", name: "student", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Year", name: "year", widget: "number"}
  - name: "contact"
    label: "Contact Info"
    folder: "data"
    create: true
    slug: "contact"
    fields:
      - {label: "Phone", name: "phone", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Schedule", name: "schedule", widget: "string"}
      - {label: "WhatsApp", name: "whatsapp", widget: "string", required: false}
      - {label: "Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Instagram", name: "instagram", widget: "string", required: false}
      - {label: "Twitter", name: "twitter", widget: "string", required: false}
